/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.spring.kafka.datagenerator.data.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroGps extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5192283413538111232L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroGps\",\"namespace\":\"org.spring.kafka.datagenerator.data.avro\",\"fields\":[{\"name\":\"long\",\"type\":\"double\"},{\"name\":\"lat\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroGps> ENCODER =
      new BinaryMessageEncoder<AvroGps>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroGps> DECODER =
      new BinaryMessageDecoder<AvroGps>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroGps> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroGps> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroGps>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroGps to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroGps from a ByteBuffer. */
  public static AvroGps fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private double long$;
   private double lat;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroGps() {}

  /**
   * All-args constructor.
   * @param long$ The new value for long
   * @param lat The new value for lat
   */
  public AvroGps(java.lang.Double long$, java.lang.Double lat) {
    this.long$ = long$;
    this.lat = lat;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return long$;
    case 1: return lat;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: long$ = (java.lang.Double)value$; break;
    case 1: lat = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'long$' field.
   * @return The value of the 'long$' field.
   */
  public java.lang.Double getLong$() {
    return long$;
  }

  /**
   * Sets the value of the 'long$' field.
   * @param value the value to set.
   */
  public void setLong$(java.lang.Double value) {
    this.long$ = value;
  }

  /**
   * Gets the value of the 'lat' field.
   * @return The value of the 'lat' field.
   */
  public java.lang.Double getLat() {
    return lat;
  }

  /**
   * Sets the value of the 'lat' field.
   * @param value the value to set.
   */
  public void setLat(java.lang.Double value) {
    this.lat = value;
  }

  /**
   * Creates a new AvroGps RecordBuilder.
   * @return A new AvroGps RecordBuilder
   */
  public static org.spring.kafka.datagenerator.data.avro.AvroGps.Builder newBuilder() {
    return new org.spring.kafka.datagenerator.data.avro.AvroGps.Builder();
  }

  /**
   * Creates a new AvroGps RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroGps RecordBuilder
   */
  public static org.spring.kafka.datagenerator.data.avro.AvroGps.Builder newBuilder(org.spring.kafka.datagenerator.data.avro.AvroGps.Builder other) {
    return new org.spring.kafka.datagenerator.data.avro.AvroGps.Builder(other);
  }

  /**
   * Creates a new AvroGps RecordBuilder by copying an existing AvroGps instance.
   * @param other The existing instance to copy.
   * @return A new AvroGps RecordBuilder
   */
  public static org.spring.kafka.datagenerator.data.avro.AvroGps.Builder newBuilder(org.spring.kafka.datagenerator.data.avro.AvroGps other) {
    return new org.spring.kafka.datagenerator.data.avro.AvroGps.Builder(other);
  }

  /**
   * RecordBuilder for AvroGps instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroGps>
    implements org.apache.avro.data.RecordBuilder<AvroGps> {

    private double long$;
    private double lat;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.spring.kafka.datagenerator.data.avro.AvroGps.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.long$)) {
        this.long$ = data().deepCopy(fields()[0].schema(), other.long$);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lat)) {
        this.lat = data().deepCopy(fields()[1].schema(), other.lat);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroGps instance
     * @param other The existing instance to copy.
     */
    private Builder(org.spring.kafka.datagenerator.data.avro.AvroGps other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.long$)) {
        this.long$ = data().deepCopy(fields()[0].schema(), other.long$);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lat)) {
        this.lat = data().deepCopy(fields()[1].schema(), other.lat);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'long$' field.
      * @return The value.
      */
    public java.lang.Double getLong$() {
      return long$;
    }

    /**
      * Sets the value of the 'long$' field.
      * @param value The value of 'long$'.
      * @return This builder.
      */
    public org.spring.kafka.datagenerator.data.avro.AvroGps.Builder setLong$(double value) {
      validate(fields()[0], value);
      this.long$ = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'long$' field has been set.
      * @return True if the 'long$' field has been set, false otherwise.
      */
    public boolean hasLong$() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'long$' field.
      * @return This builder.
      */
    public org.spring.kafka.datagenerator.data.avro.AvroGps.Builder clearLong$() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'lat' field.
      * @return The value.
      */
    public java.lang.Double getLat() {
      return lat;
    }

    /**
      * Sets the value of the 'lat' field.
      * @param value The value of 'lat'.
      * @return This builder.
      */
    public org.spring.kafka.datagenerator.data.avro.AvroGps.Builder setLat(double value) {
      validate(fields()[1], value);
      this.lat = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'lat' field has been set.
      * @return True if the 'lat' field has been set, false otherwise.
      */
    public boolean hasLat() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'lat' field.
      * @return This builder.
      */
    public org.spring.kafka.datagenerator.data.avro.AvroGps.Builder clearLat() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroGps build() {
      try {
        AvroGps record = new AvroGps();
        record.long$ = fieldSetFlags()[0] ? this.long$ : (java.lang.Double) defaultValue(fields()[0]);
        record.lat = fieldSetFlags()[1] ? this.lat : (java.lang.Double) defaultValue(fields()[1]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroGps>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroGps>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroGps>
    READER$ = (org.apache.avro.io.DatumReader<AvroGps>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
